name: flake8

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install tox
        pip install flake8==6.1.0
    - name: Run flake8 with tox
      run: |
        tox -e flake8
